import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (

    <div className={styles.container}>
      <style jsx>
        {`
        h2{
          font-size:38px
        }
        h3{
          font-size:28px
        }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Script src="./se.js" strategy='lazyOnload'></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="">Hunting Coder</span>
        </h1>
        <div className={styles.imgWrap}>
          <Image className={styles.myImg} src="/homeimg.jpg" width={237} height={158} />
        </div>
        <p className={styles.description}>
          A blog for the coders by a coder
        </p>
        <div className={styles.container}>
          <h2>Latest Blogs</h2>
          <div className="blogitem">
            <h3>How to learn javascript in 2022</h3>
            <p>Javascript is the language used to design the logic for the web</p>
          </div>
          <div className="blogitem">
            <h3>How to learn javascript in 2022</h3>
            <p>Javascript is the language used to design the logic for the web</p>
          </div>
          <div className="blogitem">
            <h3>How to learn javascript in 2022</h3>
            <p>Javascript is the language used to design the logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
